name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          PRIVATE_KEY_ID: ${{secrets.PRIVATE_KEY_ID}}
          PROJECT_ID: ${{secrets.PROJECT_ID}}
          CLIENT_EMAIL: ${{secrets.CLIENT_EMAIL}}
